// CHARACTER TYPES
export const GET_CHARACTER_LIST = "GET_CHARACTER_LIST";
export const GET_CHARACTER = "GET_CHARACTER";
export const ERROR_CHARACTER = "ERROR_CHARACTER";
export const CLEAN_CHARACTER_LIST = "CLEAN_CHARACTER_LIST";
export const GET_MORE_CHARACTER_LIST = "GET_MORE_CHARACTER_LIST";

// LOCAL TYPES
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";

// Not used

// LOCATION TYPES
export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const GET_LOCATION = "GET_LOCATION";
export const ERROR_LOCATION = "ERROR_LOCATION";

// EPISODE TYPES
export const GET_EPISODE_LIST = "GET_EPISODE_LIST";
export const GET_EPISODE = "GET_EPISODE";
export const ERROR_EPISODE = "ERROR_EPISODE";

// SEARCH TYPES
export const GET_CHARACTER_SEARCH_FILTER_LIST =
  "GET_CHARACTER_SEARCH_FILTER_LIST";
export const ERROR_CHARACTER_SEARCH_FILTER_LIST =
  "ERROR_CHARACTER_SEARCH_FILTER_LIST";
